name: Node.js CI

on: 
  push:
    branches: 
      - prove
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        dir: [./training-module]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ${{ matrix.dir }}
    - run: npm run build --if-present
      working-directory: ${{ matrix.dir }}
    - run: npm install --save jest
      working-directory: ${{ matrix.dir }}
    - run: npm test
      working-directory: ${{ matrix.dir }}
      env:
        CI: true
